"""buildwork.py end to end: a real git repository, a fake `gh` on PATH.

These run the script as a subprocess, the way SKILL.md runs it. Tests marked
`@bug(N)` reproduce an open issue and are expected to fail until it is fixed;
see harness.py.
"""

import os
import subprocess
import sys

from harness import BUILDWORK, FakeGitHub, Repo, bug, isolated_env

HOTSPOT = 'enabled = true\nrunner = "paseo"\nhotspots = ["public/_headers"]\n'

DESKWORK_ROADMAP = """\
# Roadmap

Generated by deskwork on 2026-09-17 from 6 open issues.
Order is reasoned, not computed. Every dependency shown is a declared GitHub link.

## Next

1. **#3** Third, reasoned first
   Nothing blocks it, and #4 waits on it.
2. **#1** First
3. **#2** Second

## Blocked

- **#4** Fourth - blocked by #3

## Triage - not yet in the roadmap

Filed by an agent and not yet reviewed. Listed, never ordered.

- #5 Filed by an agent
"""


def issues(github, *numbers, **bodies):
    """Open issues that each declare their own file, so none of them overlap."""
    for n in numbers:
        github.issue(n, f"issue {n}", body=bodies.get(f"b{n}", f"Change `src/f{n}.py`."))


def wave_numbers(payload):
    return [[item["issue"] for item in wave] for wave in payload["waves"]]


def remove_config(repo):
    repo.git("rm", "-q", ".github/buildwork.toml")
    repo.commit("no buildwork config")


# --- the opt-in gate --------------------------------------------------------

def test_no_config_means_no_action(repo, github, bw):
    remove_config(repo)
    issues(github, 1, 2)
    result = bw("plan", "--issues", "1,2")
    assert result.code == 1
    assert "buildwork is opt-in per repository" in result.err
    assert github.calls() == []


def test_enabled_false_means_no_action(repo, github, bw):
    repo.configure('enabled = false\nrunner = "paseo"\n')
    issues(github, 1, 2)
    result = bw("plan", "--issues", "1,2")
    assert result.code == 1
    assert "enabled = true" in result.err
    assert github.calls() == []


# --- plan -------------------------------------------------------------------

def test_plan_puts_independent_issues_in_one_wave(repo, github, bw):
    issues(github, 1, 2)
    payload = bw("plan", "--issues", "1,2", "--json").json()
    assert payload["refusal"] is None
    assert wave_numbers(payload) == [[1, 2]]
    assert payload["waves"][0][0]["branch"] == "buildwork/issue-1-issue-1"


def test_plan_refuses_one_issue(repo, github, bw):
    issues(github, 1)
    result = bw("plan", "--issues", "1")
    assert result.code == 0
    assert "DO NOT FAN OUT" in result.out
    assert "One issue (#1)" in result.out


def test_plan_reads_next_from_the_roadmap_in_its_order(repo, github, bw):
    repo.on_main("roadmap", {"roadmap.md": DESKWORK_ROADMAP})
    issues(github, 1, 2, 3, 4, 5)
    payload = bw("plan", "--json").json()
    assert payload["source"] == "roadmap.md"
    assert [n for wave in wave_numbers(payload) for n in wave] == [3, 1, 2]


def test_plan_orders_a_native_dependency(repo, github, bw):
    issues(github, 1, 2, 3)
    github.block(2, 1)
    payload = bw("plan", "--issues", "1,2,3", "--json").json()
    assert wave_numbers(payload) == [[1, 3], [2]]


def test_plan_holds_a_second_hotspot_change_back_a_wave(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "one", body="Change `public/_headers` and `src/a.py`.")
    github.issue(2, "two", body="Change `public/_headers` and `src/b.py`.")
    github.issue(3, "three", body="Change `src/c.py`.")
    result = bw("plan", "--issues", "1,2,3", "--json")
    payload = result.json()
    assert wave_numbers(payload) == [[1, 3], [2]]
    assert any("#2 waits a wave" in w for w in payload["warnings"])
    assert payload["waves"][0][0]["hotspots"] == ["public/_headers"]


def test_plan_names_roadmap_entries_that_are_not_open(repo, github, bw):
    issues(github, 1, 2)
    payload = bw("plan", "--issues", "1,2,99", "--json").json()
    assert any("#99" in w and "not open on GitHub" in w for w in payload["warnings"])


def test_plan_save_records_the_session(repo, github, bw):
    issues(github, 1, 2)
    assert bw("plan", "--goal", "ship the two fixes", "--issues", "1,2", "--save").code == 0
    status = bw("status")
    assert "Session: ship the two fixes" in status.out
    assert "Not started" in status.out


def test_plan_does_not_save_a_refusal(repo, github, bw):
    issues(github, 1)
    bw("plan", "--goal", "one thing", "--issues", "1", "--save")
    assert "No session record" in bw("status").out


# --- brief ------------------------------------------------------------------

def test_brief_carries_the_issue_the_scope_and_the_digest(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\ndigest = ["AGENTS.md"]\n')
    repo.on_main("conventions", {"AGENTS.md": "Always write tests first.\n"})
    github.issue(1, "Fix the parser", body="Change `src/parser.py`. It drops the last line.")
    result = bw("brief", "1")
    assert result.code == 0
    for expected in ("Fix the parser", "It drops the last line.", "`src/parser.py`",
                     "Closes #1", "buildwork/issue-1-fix-the-parser", "Always write tests first."):
        assert expected in result.out


def test_brief_names_the_one_permitted_hotspot(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    result = bw("brief", "1", "--allow-hotspot", "public/_headers")
    assert "permitted to touch public/_headers" in result.out


def test_brief_for_a_missing_issue_fails_with_gh_message(repo, github, bw):
    result = bw("brief", "404")
    assert result.code == 1
    assert "Could not resolve to an issue" in result.err


# --- qc ---------------------------------------------------------------------

def test_qc_passes_an_in_scope_branch_and_says_it_is_a_floor(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-one", {"src/a.py": "a\n"})
    result = bw("qc", "1")
    assert result.code == 0
    assert "a floor, not a verdict" in result.out


def test_qc_fails_a_branch_outside_its_scope(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-one", {"src/a.py": "a\n", "src/stray.py": "s\n"})
    result = bw("qc", "1")
    assert result.code == 2
    assert "outside the declared scope: src/stray.py" in result.out


def test_qc_fails_an_unpermitted_hotspot_and_passes_a_permitted_one(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "one", body="Change `public/_headers`.")
    repo.branch("buildwork/issue-1-one", {"public/_headers": "x\n"})
    assert bw("qc", "1").code == 2
    assert bw("qc", "1", "--allow-hotspot", "public/_headers").code == 0


def test_qc_ignores_what_landed_on_main_after_the_branch_was_cut(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-one", {"src/a.py": "a\n"})
    repo.on_main("somebody else", {"src/other.py": "o\n"})
    assert bw("qc", "1").code == 0


def test_qc_runs_the_gate_in_the_worker_worktree(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\ngate = "test -f ok.txt"\n')
    github.issue(1, "one")
    github.issue(2, "two")
    repo.branch("buildwork/issue-1-one", {"ok.txt": "yes\n"}, keep_worktree=True)
    repo.branch("buildwork/issue-2-two", {"other.txt": "no\n"}, keep_worktree=True)
    assert bw("qc", "1").code == 0
    failed = bw("qc", "2")
    assert failed.code == 2
    assert "gate failed" in failed.out


def test_qc_says_when_the_gate_could_not_run(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\ngate = "false"\n')
    github.issue(1, "one")
    repo.branch("buildwork/issue-1-one", {"a.txt": "a\n"})
    result = bw("qc", "1")
    assert "was not run" in result.err


def test_qc_without_a_branch_stops(repo, github, bw):
    github.issue(1, "one")
    result = bw("qc", "1")
    assert result.code == 1
    assert "No branch" in result.err


# --- order ------------------------------------------------------------------

def test_order_puts_the_smaller_diff_first(repo, github, bw):
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n" * 50})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    result = bw("order")
    assert result.code == 0
    assert result.out.index("PR #12") < result.out.index("PR #11")
    assert "buildwork does not merge" in result.out


def test_order_puts_a_blocker_first_whatever_its_size(repo, github, bw):
    issues(github, 1, 2)
    github.block(2, 1)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n" * 50})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    result = bw("order")
    assert result.out.index("PR #11") < result.out.index("PR #12")
    assert "blocked by #1" in result.out


def test_order_holds_back_a_branch_that_fails_qc(repo, github, bw):
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n", "src/stray.py": "s\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    result = bw("order")
    assert "Held back, QC not passed: #1" in result.out
    assert "PR #11" not in result.out


def test_order_flags_a_branch_with_no_pull_request(repo, github, bw):
    issues(github, 1)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    assert "No pull request yet: #1" in bw("order").out


def test_order_with_nothing_to_order_stops(repo, github, bw):
    result = bw("order")
    assert result.code == 1
    assert "Nothing to order" in result.err


def test_order_changes_nothing(repo, github, bw):
    """No merge verb: after `order`, neither main nor the remote has moved."""
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    local = repo.git("rev-parse", "main")
    remote = repo.git("rev-parse", "main", cwd=repo.remote)
    bw("order")
    assert repo.git("rev-parse", "main") == local
    assert repo.git("rev-parse", "main", cwd=repo.remote) == remote
    assert not any("merge" in arg for call in github.calls() for arg in call)


# --- status -----------------------------------------------------------------

def test_status_reconstructs_from_branches_alone(repo, github, bw):
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"}, keep_worktree=True)
    repo.branch("buildwork/issue-2-b", {"b.txt": "b\n"})
    repo.branch("buildwork/issue-3-c", {"c.txt": "c\n"})
    github.pull(12, "buildwork/issue-2-b")
    result = bw("status")
    assert "No session record" in result.out
    assert "Waiting on you" in result.out and "PR #12" in result.out
    assert "#1" in result.out and "#3" in result.out
    assert "Orphaned" in result.out


def test_status_names_a_stalled_session_branch(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"}, keep_worktree=True)
    result = bw("status")
    assert "Stalled" in result.out
    assert "Running" in result.out
    assert result.out.index("Stalled") < result.out.index("Running")


# --- doctor -----------------------------------------------------------------

def test_doctor_finds_no_drift_in_a_tidy_repository(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\ngate = "true"\n')
    repo.on_main("roadmap", {"roadmap.md": DESKWORK_ROADMAP})
    result = bw("doctor")
    assert result.code == 0
    assert "No drift found." in result.out


def test_doctor_names_a_stale_hotspot_and_a_missing_digest_file(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\nhotspots = ["gone.txt"]\ndigest = ["MISSING.md"]\n')
    result = bw("doctor")
    assert "Hotspot `gone.txt` does not exist" in result.out
    assert "Digest file `MISSING.md` does not exist" in result.out


def test_doctor_names_a_stranded_branch(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    assert "#1 on buildwork/issue-1-issue-1 has no worktree and no pull request" in bw("doctor").out


# --- init -------------------------------------------------------------------

def test_init_writes_a_disarmed_config(repo, github, bw):
    remove_config(repo)
    result = bw("init")
    assert result.code == 0
    assert "enabled = false" in (repo.root / ".github/buildwork.toml").read_text(encoding="utf-8")
    assert bw("plan").code == 1


def test_init_will_not_overwrite_without_force(repo, github, bw):
    result = bw("init")
    assert result.code == 1
    assert "already exists" in result.err
    assert bw("init", "--force").code == 0


def test_init_suggests_the_files_changed_most_often(repo, github, bw):
    remove_config(repo)
    for n in range(4):
        repo.on_main(f"touch {n}", {"src/routes.ts": f"{n}\n"})
    bw("init")
    assert '"src/routes.ts"' in (repo.root / ".github/buildwork.toml").read_text(encoding="utf-8")


# --- open bugs: each fails today, and its fix removes the marker ------------

def test_plan_reports_a_failing_gh_instead_of_nothing_to_run(repo, github, bw):
    issues(github, 1, 2)
    github.fail("issue", "list")
    result = bw("plan")
    assert result.code != 0
    assert "Bad credentials" in result.err


def test_status_reports_a_failing_gh(repo, github, bw):
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"})
    github.fail("pr", "list")
    result = bw("status")
    assert result.code != 0
    assert "Bad credentials" in result.err


def test_order_reports_a_failing_gh(repo, github, bw):
    issues(github, 1)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    github.fail("pr", "list")
    result = bw("order")
    assert result.code != 0
    assert "Bad credentials" in result.err


def test_doctor_reports_a_failing_gh_instead_of_stranded_work(repo, github, bw):
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"})
    github.fail("pr", "list")
    result = bw("doctor")
    assert result.code != 0
    assert "Bad credentials" in result.err
    assert "stranded" not in result.out


def test_doctor_reports_an_unauthenticated_gh(repo, github, bw):
    github.authenticated = False
    result = bw("doctor")
    assert result.code != 0
    assert "gh is not logged in" in result.out
    assert "gh auth login" in result.err


def test_every_command_stops_when_gh_is_not_logged_in(repo, github, bw):
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    github.authenticated = False
    for command in (["plan"], ["status"], ["order"]):
        result = bw(*command)
        assert result.code != 0, command
        assert "gh auth login" in result.err, command


def test_doctor_reports_a_clone_with_no_default_remote(repo, github, bw):
    repo.git("remote", "add", "upstream", str(repo.remote))
    result = bw("doctor")
    assert "2 remotes (origin, upstream)" in result.out
    assert "chose owner/repo on its own" in result.out
    assert "gh repo set-default" in result.out


def test_doctor_is_quiet_about_remotes_once_a_default_is_set(repo, github, bw):
    repo.git("remote", "add", "upstream", str(repo.remote))
    repo.git("config", "remote.origin.gh-resolved", "base")
    assert "set-default" not in bw("doctor").out


def test_doctor_reports_a_clone_gh_cannot_resolve(repo, github, bw):
    github.fail("repo", "view", stderr="none of the git remotes configured for this repository point to a known GitHub host")
    result = bw("doctor")
    assert result.code != 0
    assert "cannot tell which GitHub repository" in result.out
    assert "known GitHub host" in result.err


def test_order_stops_when_an_issue_cannot_be_read(repo, github, bw):
    """A failed read used to become an empty body, which switched the scope check off."""
    issues(github, 1)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n", "src/stray.py": "s\n"})
    github.fail("issue", "view", "1")
    result = bw("order")
    assert result.code != 0
    assert "Bad credentials" in result.err
    assert "Proposed merge order" not in result.out


def test_order_puts_the_permitted_hotspot_change_first(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    github.issue(2, "other", body="Change `src/b.py`.")
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n" * 50})
    repo.branch("buildwork/issue-2-other", {"src/b.py": "x\n"})
    github.pull(11, "buildwork/issue-1-headers")
    github.pull(12, "buildwork/issue-2-other")
    assert bw("qc", "1", "--allow-hotspot", "public/_headers").code == 0
    result = bw("order")
    assert "Held back" not in result.out
    assert result.out.index("PR #11") < result.out.index("PR #12")
    assert "touches public/_headers" in result.out


def hotspot_wave(repo, github, bw):
    """#1 is sent to change the hotspot, #2 is not. Both are planned and saved."""
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    github.issue(2, "other", body="Change `src/b.py`.")
    assert bw("plan", "--goal", "g", "--issues", "1,2", "--save").code == 0


def test_qc_reads_the_hotspot_permission_from_the_session(repo, github, bw):
    """SKILL.md runs `qc N` bare at collection. The branch sent to change the hotspot must pass."""
    hotspot_wave(repo, github, bw)
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n"})
    result = bw("qc", "1")
    assert result.code == 0, result.out


def test_only_the_issue_sent_to_change_a_hotspot_may_touch_it(repo, github, bw):
    hotspot_wave(repo, github, bw)
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n"})
    repo.branch("buildwork/issue-2-other", {"src/b.py": "x\n", "public/_headers": "y\n"})
    github.pull(11, "buildwork/issue-1-headers")
    github.pull(12, "buildwork/issue-2-other")
    assert bw("qc", "2").code == 2
    result = bw("order")
    assert "Held back, QC not passed: #2" in result.out
    assert "1. PR #11" in result.out


def test_order_without_a_session_knows_no_permission_and_holds_a_hotspot_branch(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n"})
    github.pull(11, "buildwork/issue-1-headers")
    assert "Held back, QC not passed: #1" in bw("order").out


def merged_wave(repo, github, bw):
    """A wave of two where #1 was squash-merged on GitHub and #2 is still open."""
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    repo.merge_on_github("buildwork/issue-1-issue-1")
    github.pull(11, "buildwork/issue-1-issue-1", state="MERGED")
    github.pull(12, "buildwork/issue-2-issue-2")


def test_status_shows_a_merged_pull_request_as_merged(repo, github, bw):
    merged_wave(repo, github, bw)
    result = bw("status")
    assert "Stalled" not in result.out
    assert "Merged - done" in result.out
    assert "#1  merged  buildwork/issue-1-issue-1  PR #11" in result.out


def test_doctor_does_not_call_merged_work_stranded(repo, github, bw):
    merged_wave(repo, github, bw)
    assert "stranded" not in bw("doctor").out


def test_order_leaves_out_merged_and_closed_pull_requests(repo, github, bw):
    merged_wave(repo, github, bw)
    github.issue(3, "issue 3", body="Change `src/f3.py`.")
    repo.branch("buildwork/issue-3-issue-3", {"src/f3.py": "x\n"})
    github.pull(13, "buildwork/issue-3-issue-3", state="CLOSED")
    result = bw("order")
    assert "1. PR #12 (closes #2)" in result.out
    for gone in ("(closes #1)", "issue-1-", "PR #11", "(closes #3)", "issue-3-", "PR #13"):
        assert gone not in result.out


def test_order_says_when_everything_is_already_merged(repo, github, bw):
    merged_wave(repo, github, bw)
    repo.merge_on_github("buildwork/issue-2-issue-2")
    github.pull(12, "buildwork/issue-2-issue-2", state="MERGED")
    result = bw("order")
    assert result.code == 0
    assert "Nothing left to merge" in result.out
    assert "PR #" not in result.out


def test_status_shows_a_closed_pull_request_as_done(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1", state="CLOSED")
    result = bw("status")
    assert "Closed without merging" in result.out
    assert "Stalled" not in result.out


@bug(8)
def test_doctor_warns_when_the_local_base_is_behind_its_remote(repo, github, bw):
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"})
    repo.merge_on_github("buildwork/issue-1-a")
    repo.git("fetch", "-q", "origin")
    assert "behind" in bw("doctor").out


@bug(10)
def test_an_open_blocker_outside_the_selection_holds_the_issue(repo, github, bw):
    issues(github, 4, 5, 6, 9)
    github.block(4, 9)
    payload = bw("plan", "--issues", "4,5,6", "--json").json()
    assert 4 not in [n for wave in wave_numbers(payload) for n in wave]
    assert any("#9" in w for w in payload["warnings"])


@bug(11)
def test_plan_says_when_no_dependency_source_answered(repo, github, bw):
    issues(github, 1, 2)
    github.dependencies_api = False
    github.blocked_by_field = False
    assert "No dependency links were readable" in bw("plan", "--issues", "1,2").out


@bug(11)
def test_a_blocker_in_another_repository_is_not_a_local_issue(repo, github, bw):
    issues(github, 1, 2, 3)
    github.block(1, {"repo": "owner/other", "number": 2, "state": "CLOSED"})
    payload = bw("plan", "--issues", "1,2,3", "--json").json()
    assert wave_numbers(payload) == [[1, 2, 3]]


@bug(11)
def test_blockers_past_the_first_page_are_read(repo, github, bw):
    for n in range(100, 130):
        github.issue(n, state="CLOSED")
    issues(github, 1, 130)
    github.block(1, *range(100, 131))
    payload = bw("plan", "--issues", "1,130", "--json").json()
    assert wave_numbers(payload) == [[130], [1]]


@bug(12)
def test_auto_runner_without_a_runner_flag_refuses(repo, github, bw):
    repo.configure('enabled = true\nrunner = "auto"\n')
    issues(github, 1, 2)
    result = bw("plan", "--issues", "1,2")
    assert result.code != 0
    assert "--runner" in result.text


@bug(13)
def test_plan_will_not_take_every_open_issue_without_all(repo, github, bw):
    issues(github, 1, 2, 3)
    result = bw("plan", "--goal", "only the parser")
    assert "Wave 1" not in result.out
    assert "--all" in result.text


@bug(16)
def test_qc_finds_the_branch_after_the_issue_is_retitled(repo, github, bw):
    github.issue(1, "a better title", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-the-original-title", {"src/a.py": "a\n"})
    assert bw("qc", "1").code == 0


@bug(16)
def test_status_from_a_linked_worktree_finds_the_session(repo, github, bw, tmp_path):
    issues(github, 1, 2)
    bw("plan", "--goal", "from the main checkout", "--issues", "1,2", "--save")
    repo.git("branch", "orchestrator", "main")
    linked = repo.worktree(tmp_path / "orchestrator-checkout", "orchestrator")
    assert "Session: from the main checkout" in bw("status", cwd=linked).out


@bug(16)
def test_two_repositories_with_the_same_folder_name_keep_separate_sessions(repo, github, bw, tmp_path, home):
    other_gh = FakeGitHub(home=tmp_path / "gh-other", repo="owner/other")
    other = Repo(tmp_path / "elsewhere", isolated_env(home))
    assert other.root.name == repo.root.name
    for fake in (github, other_gh):
        issues(fake, 1, 2)

    env = {**os.environ, **isolated_env(home), **other_gh.env()}
    subprocess.run(
        [sys.executable, str(BUILDWORK), "plan", "--goal", "the other one", "--issues", "1,2", "--save"],
        cwd=other.root, env=env, capture_output=True, text=True, check=True,
    )
    bw("plan", "--goal", "this one", "--issues", "1,2", "--save")
    result = subprocess.run(
        [sys.executable, str(BUILDWORK), "status"],
        cwd=other.root, env=env, capture_output=True, text=True, check=True,
    )
    assert "Session: the other one" in result.stdout
