"""buildwork.py end to end: a real git repository, a fake `gh` on PATH.

These run the script as a subprocess, the way SKILL.md runs it. Tests marked
`@bug(N)` reproduce an open issue and are expected to fail until it is fixed;
see harness.py.
"""

import os
import re
import subprocess
import sys

from harness import BUILDWORK, FakeGitHub, Repo, isolated_env

HOTSPOT = 'enabled = true\nrunner = "paseo"\nhotspots = ["public/_headers"]\n'

DESKWORK_ROADMAP = """\
# Roadmap

Generated by deskwork on 2026-09-17 from 6 open issues.
Order is reasoned, not computed. Every dependency shown is a declared GitHub link.

## Next

1. **#3** Third, reasoned first
   Nothing blocks it, and #4 waits on it.
2. **#1** First
3. **#2** Second

## Blocked

- **#4** Fourth - blocked by #3

## Triage - not yet in the roadmap

Filed by an agent and not yet reviewed. Listed, never ordered.

- #5 Filed by an agent
"""


def issues(github, *numbers, **bodies):
    """Open issues that each declare their own file, so none of them overlap."""
    for n in numbers:
        github.issue(n, f"issue {n}", body=bodies.get(f"b{n}", f"Change `src/f{n}.py`."))


def wave_numbers(payload):
    return [[item["issue"] for item in wave] for wave in payload["waves"]]


def remove_config(repo):
    repo.git("rm", "-q", ".github/buildwork.toml")
    repo.commit("no buildwork config")


# --- the opt-in gate --------------------------------------------------------

def test_no_config_means_no_action(repo, github, bw):
    remove_config(repo)
    issues(github, 1, 2)
    result = bw("plan", "--issues", "1,2")
    assert result.code == 1
    assert "buildwork is opt-in per repository" in result.err
    assert github.calls() == []


def test_enabled_false_means_no_action(repo, github, bw):
    repo.configure('enabled = false\nrunner = "paseo"\n')
    issues(github, 1, 2)
    result = bw("plan", "--issues", "1,2")
    assert result.code == 1
    assert "enabled = true" in result.err
    assert github.calls() == []


# --- plan -------------------------------------------------------------------

def test_plan_puts_independent_issues_in_one_wave(repo, github, bw):
    issues(github, 1, 2)
    payload = bw("plan", "--issues", "1,2", "--json").json()
    assert payload["refusal"] is None
    assert wave_numbers(payload) == [[1, 2]]
    assert payload["waves"][0][0]["branch"] == "buildwork/issue-1-issue-1"


def test_plan_refuses_one_issue(repo, github, bw):
    issues(github, 1)
    result = bw("plan", "--issues", "1")
    assert result.code == 0
    assert "DO NOT FAN OUT" in result.out
    assert "One issue (#1)" in result.out


def test_plan_reads_next_from_the_roadmap_in_its_order(repo, github, bw):
    repo.on_main("roadmap", {"roadmap.md": DESKWORK_ROADMAP})
    issues(github, 1, 2, 3, 4, 5)
    payload = bw("plan", "--json").json()
    assert payload["source"] == "roadmap.md"
    assert [n for wave in wave_numbers(payload) for n in wave] == [3, 1, 2]


def test_plan_orders_a_native_dependency(repo, github, bw):
    issues(github, 1, 2, 3)
    github.block(2, 1)
    payload = bw("plan", "--issues", "1,2,3", "--json").json()
    assert wave_numbers(payload) == [[1, 3], [2]]


def test_plan_holds_a_second_hotspot_change_back_a_wave(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "one", body="Change `public/_headers` and `src/a.py`.")
    github.issue(2, "two", body="Change `public/_headers` and `src/b.py`.")
    github.issue(3, "three", body="Change `src/c.py`.")
    result = bw("plan", "--issues", "1,2,3", "--json")
    payload = result.json()
    assert wave_numbers(payload) == [[1, 3], [2]]
    assert any("#2 waits a wave" in w for w in payload["warnings"])
    assert payload["waves"][0][0]["hotspots"] == ["public/_headers"]


def test_plan_warns_on_an_issue_from_outside_the_repository(repo, github, bw):
    """Its body becomes a worker's instructions. On a public repository anyone can write one."""
    github.issue(1, "ours", body="Change `src/a.py`.", author="alice", association="OWNER")
    github.issue(2, "theirs", body="Change `src/b.py`.", author="stranger", association="NONE")
    out = bw("plan", "--issues", "1,2").out
    assert "#1  ours  (by @alice, owner)" in out
    assert "#2  theirs  (by @stranger, none)" in out
    warnings = [line for line in out.splitlines() if line.startswith("! ")]
    assert warnings == [
        "! #2 was opened by @stranger, who is not an owner, member or collaborator here "
        "(GitHub says NONE). Its body goes into a worker's brief word for word: read it before you approve."
    ]


def test_plan_trusts_owners_members_and_collaborators_and_no_one_else(repo, github, bw):
    kinds = ["OWNER", "MEMBER", "COLLABORATOR", "CONTRIBUTOR", "FIRST_TIME_CONTRIBUTOR", "FIRST_TIMER", "NONE"]
    for n, kind in enumerate(kinds, 1):
        github.issue(n, f"issue {n}", body=f"Change `src/f{n}.py`.", author=f"user{n}", association=kind)
    payload = bw("plan", "--issues", ",".join(str(n) for n in range(1, len(kinds) + 1)), "--json").json()
    warned = sorted(int(w.split()[0][1:]) for w in payload["warnings"] if "not an owner, member or collaborator" in w)
    assert warned == [4, 5, 6, 7]
    item = next(i for wave in payload["waves"] for i in wave if i["issue"] == 7)
    assert (item["author"], item["association"]) == ("user7", "NONE")


def test_plan_says_when_it_could_not_check_who_opened_the_issues(repo, github, bw):
    issues(github, 1, 2)
    github.fail("api", "graphql", stderr="gh: API rate limit exceeded")
    result = bw("plan", "--issues", "1,2")
    assert result.code == 0, result.text
    assert "Could not read who opened #1, #2, so none was checked" in result.out
    assert "rate limit" in result.out


def test_plan_names_roadmap_entries_that_are_not_open(repo, github, bw):
    issues(github, 1, 2)
    payload = bw("plan", "--issues", "1,2,99", "--json").json()
    assert any("#99" in w and "not open on GitHub" in w for w in payload["warnings"])


def test_plan_save_records_the_session(repo, github, bw):
    issues(github, 1, 2)
    assert bw("plan", "--goal", "ship the two fixes", "--issues", "1,2", "--save").code == 0
    status = bw("status")
    assert "Session: ship the two fixes" in status.out
    assert "Not started" in status.out


def test_plan_does_not_save_a_refusal(repo, github, bw):
    issues(github, 1)
    bw("plan", "--goal", "one thing", "--issues", "1", "--save")
    assert "No session record" in bw("status").out


# --- brief ------------------------------------------------------------------

def test_brief_carries_the_issue_the_scope_and_the_digest(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\ndigest = ["AGENTS.md"]\n')
    repo.on_main("conventions", {"AGENTS.md": "Always write tests first.\n"})
    github.issue(1, "Fix the parser", body="Change `src/parser.py`. It drops the last line.")
    result = bw("brief", "1")
    assert result.code == 0
    for expected in ("Fix the parser", "It drops the last line.", "`src/parser.py`",
                     "Closes #1", "buildwork/issue-1-fix-the-parser", "Always write tests first."):
        assert expected in result.out


def test_a_redispatch_brief_tells_the_worker_to_build_on_the_earlier_commits(repo, github, bw):
    github.issue(1, "Fix the parser", body="Change `src/parser.py`.")
    repo.branch("buildwork/issue-1-fix-the-parser", {"src/parser.py": "half done\n"})
    brief = bw("brief", "1", "--runner", "paseo").out
    assert "An earlier worker started this issue" in brief
    assert "1 commit(s) are already on `buildwork/issue-1-fix-the-parser`" in brief
    assert "git log origin/main..HEAD" in brief


def test_a_first_dispatch_brief_mentions_no_earlier_work(repo, github, bw):
    github.issue(1, "Fix the parser", body="Change `src/parser.py`.")
    assert "earlier worker" not in bw("brief", "1", "--runner", "paseo").out
    # Paseo made the workspace first: the branch exists, and nothing is on it yet.
    repo.branch("buildwork/issue-1-fix-the-parser", keep_worktree=True)
    assert "earlier worker" not in bw("brief", "1", "--runner", "paseo").out


def test_brief_names_the_one_permitted_hotspot(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    result = bw("brief", "1", "--allow-hotspot", "public/_headers")
    assert "permitted to touch `public/_headers`" in result.out


def test_brief_names_the_gate_and_every_configured_hotspot(repo, github, bw):
    repo.configure(
        'enabled = true\nrunner = "paseo"\ngate = "make check"\n'
        'hotspots = ["public/_headers", "src/routes.ts"]\n'
    )
    github.issue(1, "one", body="Change `src/a.py`.")
    out = bw("brief", "1").out
    assert "run `make check` in your worktree" in out
    assert "- `public/_headers`\n- `src/routes.ts`" in out
    assert "permitted" not in out


def test_brief_reads_the_hotspot_permission_from_the_session_as_qc_does(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    github.issue(2, "other", body="Change `src/other.py`.")
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    assert "permitted to touch `public/_headers`" in bw("brief", "1").out
    other = bw("brief", "2").out
    assert "permitted" not in other and "- `public/_headers`" in other


# A Claude Code worktree subagent's branch, as the Agent tool returns it in
# `worktreeBranch`, cut from origin/<default branch> whatever the config says.
AGENT_BRANCH = "worktree-agent-a1b2c3d4e5f6a7b8"
FIRST_STEP = re.compile(r"`(git [^`]+)`")


def subagent_worktree(repo, from_ref="origin/main"):
    """The worktree the host makes: its own branch name, its own choice of base."""
    repo.git("fetch", "-q", "origin")
    tree = repo.trees / "agent-a1b2c3d4e5f6a7b8"
    repo.git("worktree", "add", "-q", "-b", AGENT_BRANCH, str(tree), from_ref)
    return tree


def first_section(brief):
    """The brief up to its second heading: what the worker does before anything else."""
    heads = [m.start() for m in re.finditer(r"^## ", brief, re.M)]
    return brief[heads[0]:heads[1]]


def run_first_step(repo, tree, brief):
    """Run the brief's first-step git commands in the worker's tree, as the worker would."""
    outputs = []
    for command in FIRST_STEP.findall(first_section(brief)):
        outputs.append(repo.git(*command.split()[1:], cwd=tree).strip())
    return outputs


def test_a_subagent_brief_opens_by_renaming_the_branch_and_checking_the_base(repo, github, bw):
    github.issue(1, "Fix the parser", body="Change `src/parser.py`.")
    brief = bw("brief", "1", "--runner", "subagent").out
    first = first_section(brief)
    assert first.startswith("## Before anything else")
    assert FIRST_STEP.findall(first) == [
        "git branch -m buildwork/issue-1-fix-the-parser",
        "git branch --show-current",
        "git rev-parse HEAD",
        "git rev-parse origin/main",
    ]
    assert "stop" in first
    assert brief.index("## Before anything else") < brief.index("## Task")


def test_a_paseo_brief_does_not_ask_for_a_rename(repo, github, bw):
    github.issue(1, "Fix the parser", body="Change `src/parser.py`.")
    brief = bw("brief", "1", "--runner", "paseo").out
    assert brief.startswith("## Task")
    assert "git branch -m" not in brief
    assert "already checked out" in brief


def test_brief_takes_the_runner_from_the_saved_session(repo, github, bw):
    repo.configure('enabled = true\nrunner = "subagent"\n')
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.configure('enabled = true\nrunner = "auto"\n')
    assert "git branch -m" in bw("brief", "1").out


def test_brief_will_not_guess_the_runner(repo, github, bw):
    repo.configure('enabled = true\nrunner = "auto"\n')
    github.issue(1, "one")
    result = bw("brief", "1")
    assert result.code == 1
    assert "--runner" in result.err


def test_a_subagent_worker_that_follows_its_brief_is_found_by_qc_and_status(repo, github, bw):
    repo.configure('enabled = true\nrunner = "subagent"\ngate = "test -f src/parser.py"\n')
    github.issue(1, "Fix the parser", body="Change `src/parser.py`.")
    github.issue(2, "Other", body="Change `src/other.py`.")
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    tree = subagent_worktree(repo)

    renamed, current, head, base = run_first_step(repo, tree, bw("brief", "1").out)
    assert current == "buildwork/issue-1-fix-the-parser"
    assert head == base

    repo.commit("fix the parser", {"src/parser.py": "fixed\n"}, cwd=tree)
    status = bw("status").out
    assert "Running" in status
    assert f"#1  running  buildwork/issue-1-fix-the-parser  {tree.name}" in status
    result = bw("qc", "1")
    assert result.code == 0, result.text
    assert "gate" in result.out and "was not run" not in result.err


def test_a_subagent_cut_from_the_wrong_base_fails_its_first_check(repo, github, bw):
    """base = "develop", but the host cut the worktree from origin/main, its default branch."""
    repo.git("branch", "develop", "main")
    repo.git("push", "-q", "origin", "develop")
    repo.configure('enabled = true\nrunner = "subagent"\nbase = "develop"\n')
    github.issue(1, "one", body="Change `src/a.py`.")
    tree = subagent_worktree(repo, from_ref="origin/main")

    renamed, current, head, base = run_first_step(repo, tree, bw("brief", "1").out)
    assert current == "buildwork/issue-1-one"
    assert head != base


def test_qc_collects_a_worker_that_never_renamed_its_branch(repo, github, bw):
    """It stopped before the rename. The orchestrator passes the worktreeBranch it was given."""
    repo.configure('enabled = true\nrunner = "subagent"\ngate = "test -f src/a.py"\n')
    github.issue(1, "one", body="Change `src/a.py`.")
    tree = subagent_worktree(repo)
    repo.commit("work", {"src/a.py": "a\n"}, cwd=tree)
    result = bw("qc", "1", "--branch", AGENT_BRANCH)
    assert result.code == 0, result.text
    assert "was not run" not in result.err


def test_brief_for_a_missing_issue_fails_with_gh_message(repo, github, bw):
    result = bw("brief", "404")
    assert result.code == 1
    assert "Could not resolve to an issue" in result.err


# --- qc ---------------------------------------------------------------------

def test_qc_passes_an_in_scope_branch_and_says_it_is_a_floor(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-one", {"src/a.py": "a\n"})
    result = bw("qc", "1")
    assert result.code == 0
    assert "a floor, not a verdict" in result.out


def test_qc_fails_a_branch_outside_its_scope(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-one", {"src/a.py": "a\n", "src/stray.py": "s\n"})
    result = bw("qc", "1")
    assert result.code == 2
    assert "outside the declared scope: src/stray.py" in result.out


def test_qc_fails_an_unpermitted_hotspot_and_passes_a_permitted_one(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "one", body="Change `public/_headers`.")
    repo.branch("buildwork/issue-1-one", {"public/_headers": "x\n"})
    assert bw("qc", "1").code == 2
    assert bw("qc", "1", "--allow-hotspot", "public/_headers").code == 0


def test_qc_ignores_what_landed_on_main_after_the_branch_was_cut(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-one", {"src/a.py": "a\n"})
    repo.on_main("somebody else", {"src/other.py": "o\n"})
    assert bw("qc", "1").code == 0


def test_qc_runs_the_gate_in_the_worker_worktree(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\ngate = "test -f ok.txt"\n')
    github.issue(1, "one")
    github.issue(2, "two")
    repo.branch("buildwork/issue-1-one", {"ok.txt": "yes\n"}, keep_worktree=True)
    repo.branch("buildwork/issue-2-two", {"other.txt": "no\n"}, keep_worktree=True)
    assert bw("qc", "1").code == 0
    failed = bw("qc", "2")
    assert failed.code == 2
    assert "gate failed" in failed.out


def test_qc_says_when_the_gate_could_not_run(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\ngate = "false"\n')
    github.issue(1, "one")
    repo.branch("buildwork/issue-1-one", {"a.txt": "a\n"})
    result = bw("qc", "1")
    assert "was not run" in result.err


def test_qc_fails_a_branch_that_adds_a_credential(repo, github, bw):
    token = "gh" + "p_" + "a1B2" * 9
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-one", {"src/a.py": f'TOKEN = "{token}"\n'})
    result = bw("qc", "1")
    assert result.code == 2
    assert "[FAIL] secrets: a GitHub token in src/a.py" in result.out
    assert token not in result.text


def test_qc_passes_a_branch_with_no_credential_and_says_it_scanned(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-one", {"src/a.py": "a\n"})
    result = bw("qc", "1")
    assert result.code == 0
    assert "[pass] secrets: no known credential shape in 1 added line(s)" in result.out


def test_order_holds_back_a_branch_that_adds_a_credential(repo, github, bw):
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "-----BEGIN " + "RSA PRIVATE KEY-----\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    out = bw("order").out
    assert "Held back" in out and "#1" in out.split("Held back", 1)[1]


def test_qc_without_a_branch_stops(repo, github, bw):
    github.issue(1, "one")
    result = bw("qc", "1")
    assert result.code == 1
    assert "No branch" in result.err


# --- order ------------------------------------------------------------------

def test_order_puts_the_smaller_diff_first(repo, github, bw):
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n" * 50})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    result = bw("order")
    assert result.code == 0
    assert result.out.index("PR #12") < result.out.index("PR #11")
    assert "buildwork does not merge" in result.out


def test_order_puts_a_blocker_first_whatever_its_size(repo, github, bw):
    issues(github, 1, 2)
    github.block(2, 1)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n" * 50})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    result = bw("order")
    assert result.out.index("PR #11") < result.out.index("PR #12")
    assert "blocked by #1" in result.out


def test_order_holds_back_a_branch_that_fails_qc(repo, github, bw):
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n", "src/stray.py": "s\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    result = bw("order")
    assert "Held back, QC not passed: #1" in result.out
    assert "PR #11" not in result.out


def test_order_flags_a_branch_with_no_pull_request(repo, github, bw):
    issues(github, 1)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    assert "No pull request yet: #1" in bw("order").out


def test_order_with_nothing_to_order_stops(repo, github, bw):
    result = bw("order")
    assert result.code == 1
    assert "Nothing to order" in result.err


def _undeclared(github, *numbers):
    """Issues that name no files, as most do. Nothing in the plan can see what they will touch."""
    for n in numbers:
        github.issue(n, f"issue {n}", body="Fix the thing.")


def test_order_finds_a_conflict_on_a_file_no_issue_declared(repo, github, bw):
    repo.on_main("seed", {"src/shared.py": "one\ntwo\nthree\n"})
    _undeclared(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/shared.py": "ONE\ntwo\nthree\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/shared.py": "uno\ntwo\nthree\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    out = bw("order").out
    assert "PR #11 and PR #12 conflict with each other in src/shared.py." in out
    assert "rebases it onto origin/main" in out


def test_order_finds_a_conflict_with_work_merged_since_the_branch_was_cut(repo, github, bw):
    repo.on_main("seed", {"src/shared.py": "one\ntwo\n"})
    _undeclared(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/shared.py": "ONE\ntwo\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/other.py": "x\n"})
    repo.branch("elsewhere", {"src/shared.py": "uno\ntwo\n"})
    repo.merge_on_github("elsewhere")
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    out = bw("order").out
    assert "PR #11 conflicts with origin/main in src/shared.py." in out
    assert "PR #12" in out and "PR #12 conflicts" not in out


# Found by searching random edits: every pair of these merges cleanly, and
# each merges cleanly into main, but the third conflicts once the first two
# are in. Checking pairs alone cannot see it.
SEQUENCE_BASE = "b\nb\na\nb\na\na\n"
SEQUENCE_BRANCHES = {
    1: "b\nb\nc\na\nb\na\na\n",   # one line added: the smallest diff, so first
    2: "X\nb\na\nb\na\na\n",       # the first line changed
    3: "X\nb\na\nb\na\nc\n",       # the same first line, and the last one
}


def test_order_finds_a_conflict_that_only_the_proposed_order_shows(repo, github, bw):
    repo.on_main("seed", {"notes.txt": SEQUENCE_BASE})
    _undeclared(github, 1, 2, 3)
    for n, text in SEQUENCE_BRANCHES.items():
        repo.branch(f"buildwork/issue-{n}-issue-{n}", {"notes.txt": text})
        github.pull(10 + n, f"buildwork/issue-{n}-issue-{n}")
    out = bw("order").out
    assert out.index("PR #11") < out.index("PR #12") < out.index("PR #13")
    assert "conflict with each other" not in out
    assert "conflicts with origin/main" not in out
    assert "In this order, PR #13 conflicts once PR #11, PR #12 have merged, in notes.txt." in out


def test_order_says_when_nothing_conflicts(repo, github, bw):
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    assert "No conflicts: each branch merges cleanly into origin/main" in bw("order").out


def test_the_conflict_check_moves_no_ref_and_touches_no_file(repo, github, bw):
    repo.on_main("seed", {"src/shared.py": "one\n"})
    _undeclared(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/shared.py": "ONE\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/shared.py": "uno\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    refs = repo.git("for-each-ref", "--format=%(refname) %(objectname)")
    remote = repo.git("for-each-ref", "--format=%(refname) %(objectname)", cwd=repo.remote)
    assert "conflict with each other" in bw("order").out
    assert repo.git("for-each-ref", "--format=%(refname) %(objectname)") == refs
    assert repo.git("for-each-ref", "--format=%(refname) %(objectname)", cwd=repo.remote) == remote
    assert repo.git("status", "--porcelain") == ""


def test_the_brief_lets_a_worker_rebase_its_own_branch_only_as_its_rework(repo, github, bw):
    issues(github, 1)
    out = " ".join(bw("brief", "1", "--runner", "paseo").out.split())
    assert "Do not rebase, unless the orchestrator sends it back as your one rework" in out
    assert "rebase this branch and only this branch onto `origin/main`" in out
    assert "--force-with-lease" in out


def test_order_changes_nothing(repo, github, bw):
    """No merge verb: after `order`, neither main nor the remote has moved."""
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    local = repo.git("rev-parse", "main")
    remote = repo.git("rev-parse", "main", cwd=repo.remote)
    bw("order")
    assert repo.git("rev-parse", "main") == local
    assert repo.git("rev-parse", "main", cwd=repo.remote) == remote
    assert not any("merge" in arg for call in github.calls() for arg in call)


# --- status -----------------------------------------------------------------

def test_status_reconstructs_from_branches_alone(repo, github, bw):
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"}, keep_worktree=True)
    repo.branch("buildwork/issue-2-b", {"b.txt": "b\n"})
    repo.branch("buildwork/issue-3-c", {"c.txt": "c\n"})
    github.pull(12, "buildwork/issue-2-b")
    result = bw("status")
    assert "No session record" in result.out
    assert "Waiting on you" in result.out and "PR #12" in result.out
    assert "#1" in result.out and "#3" in result.out
    assert "Orphaned" in result.out


def test_status_names_a_stalled_session_branch(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"}, keep_worktree=True)
    result = bw("status")
    assert "Stalled" in result.out
    assert "Running" in result.out
    assert result.out.index("Stalled") < result.out.index("Running")


def test_status_shows_a_worktree_with_no_live_agent_as_stalled(repo, github, bw):
    """A dead agent leaves its worktree behind. With the runner's list, that is a stall."""
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"}, keep_worktree=True)
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"}, keep_worktree=True)
    result = bw("status", "--live", "2")
    assert result.code == 0, result.text
    stalled, running = result.out.split("Running:")
    assert "Stalled" in stalled and "#1  stalled" in stalled
    assert "#2  running" in running and "#1" not in running


def test_status_with_no_live_agents_shows_every_open_worktree_as_stalled(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"}, keep_worktree=True)
    result = bw("status", "--live", "none")
    assert "#1  stalled" in result.out
    assert "Running" not in result.out


def test_status_without_the_agent_list_says_running_is_a_guess(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"}, keep_worktree=True)
    result = bw("status")
    assert "#1  running" in result.out
    assert "not that an agent is in it" in result.out and "--live" in result.out


def test_status_refuses_a_live_list_that_is_not_issue_numbers(repo, github, bw):
    result = bw("status", "--live", "agent-3")
    assert result.code == 2
    assert "--live none" in result.err


# --- doctor -----------------------------------------------------------------

def test_doctor_finds_no_drift_in_a_tidy_repository(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\ngate = "true"\n')
    repo.on_main("roadmap", {"roadmap.md": DESKWORK_ROADMAP})
    result = bw("doctor")
    assert result.code == 0
    assert "No drift found." in result.out


def test_doctor_names_a_stale_hotspot_and_a_missing_digest_file(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\nhotspots = ["gone.txt"]\ndigest = ["MISSING.md"]\n')
    result = bw("doctor")
    assert "Hotspot `gone.txt` does not exist" in result.out
    assert "Digest file `MISSING.md` does not exist" in result.out


def test_doctor_names_a_stranded_branch(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    assert "#1 on buildwork/issue-1-issue-1 has no worktree, and no pull request" in bw("doctor").out


def test_doctor_gives_a_stranded_branch_a_next_step(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    out = bw("doctor").out
    assert "Next:" in out
    assert "re-dispatch a worker onto buildwork/issue-1-issue-1" in out
    assert "one rework" in out


def test_doctor_names_a_worktree_with_no_live_agent(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    tree = repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"}, keep_worktree=True)
    assert "stranded" not in bw("doctor").out
    out = bw("doctor", "--live", "none").out
    assert f"still has its worktree ({tree.name}) but no working agent" in out
    assert "Next:" in out


# --- init -------------------------------------------------------------------

def test_init_writes_a_disarmed_config(repo, github, bw):
    remove_config(repo)
    result = bw("init")
    assert result.code == 0
    assert "enabled = false" in (repo.root / ".github/buildwork.toml").read_text(encoding="utf-8")
    assert bw("plan").code == 1


def test_init_will_not_overwrite_without_force(repo, github, bw):
    result = bw("init")
    assert result.code == 1
    assert "already exists" in result.err
    assert bw("init", "--force").code == 0


def test_init_does_not_suggest_a_file_that_was_deleted(repo, github, bw):
    remove_config(repo)
    for n in range(4):
        repo.on_main(f"touch {n}", {"src/routes.ts": f"{n}\n", "src/old.ts": f"{n}\n"})
    repo.git("rm", "-q", "src/old.ts")
    repo.commit("remove old.ts")
    bw("init")
    config = (repo.root / ".github/buildwork.toml").read_text(encoding="utf-8")
    assert '"src/routes.ts"' in config
    assert "src/old.ts" not in config


def test_init_suggests_the_files_changed_most_often(repo, github, bw):
    remove_config(repo)
    for n in range(4):
        repo.on_main(f"touch {n}", {"src/routes.ts": f"{n}\n"})
    bw("init")
    assert '"src/routes.ts"' in (repo.root / ".github/buildwork.toml").read_text(encoding="utf-8")


# --- the branch and the session are found by what does not change -----------

def test_plan_reports_a_failing_gh_instead_of_nothing_to_run(repo, github, bw):
    issues(github, 1, 2)
    github.fail("issue", "list")
    result = bw("plan", "--all")
    assert result.code != 0
    assert "Bad credentials" in result.err


def test_status_reports_a_failing_gh(repo, github, bw):
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"})
    github.fail("pr", "list")
    result = bw("status")
    assert result.code != 0
    assert "Bad credentials" in result.err


def test_order_reports_a_failing_gh(repo, github, bw):
    issues(github, 1)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    github.fail("pr", "list")
    result = bw("order")
    assert result.code != 0
    assert "Bad credentials" in result.err


def test_doctor_reports_a_failing_gh_instead_of_stranded_work(repo, github, bw):
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"})
    github.fail("pr", "list")
    result = bw("doctor")
    assert result.code != 0
    assert "Bad credentials" in result.err
    assert "stranded" not in result.out


def test_doctor_reports_an_unauthenticated_gh(repo, github, bw):
    github.authenticated = False
    result = bw("doctor")
    assert result.code != 0
    assert "gh is not logged in" in result.out
    assert "gh auth login" in result.err


def test_every_command_stops_when_gh_is_not_logged_in(repo, github, bw):
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    github.authenticated = False
    for command in (["plan", "--issues", "1,2"], ["status"], ["order"]):
        result = bw(*command)
        assert result.code != 0, command
        assert "gh auth login" in result.err, command


def test_doctor_reports_a_clone_with_no_default_remote(repo, github, bw):
    repo.git("remote", "add", "upstream", str(repo.remote))
    result = bw("doctor")
    assert "2 remotes (origin, upstream)" in result.out
    assert "chose owner/repo on its own" in result.out
    assert "gh repo set-default" in result.out


def test_doctor_is_quiet_about_remotes_once_a_default_is_set(repo, github, bw):
    repo.git("remote", "add", "upstream", str(repo.remote))
    repo.git("config", "remote.origin.gh-resolved", "base")
    assert "set-default" not in bw("doctor").out


def test_doctor_reports_a_clone_gh_cannot_resolve(repo, github, bw):
    github.fail("repo", "view", stderr="none of the git remotes configured for this repository point to a known GitHub host")
    result = bw("doctor")
    assert result.code != 0
    assert "cannot tell which GitHub repository" in result.out
    assert "known GitHub host" in result.err


def test_order_stops_when_an_issue_cannot_be_read(repo, github, bw):
    """A failed read used to become an empty body, which switched the scope check off."""
    issues(github, 1)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n", "src/stray.py": "s\n"})
    github.fail("issue", "view", "1")
    result = bw("order")
    assert result.code != 0
    assert "Bad credentials" in result.err
    assert "Proposed merge order" not in result.out


def test_order_puts_the_permitted_hotspot_change_first(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    github.issue(2, "other", body="Change `src/b.py`.")
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n" * 50})
    repo.branch("buildwork/issue-2-other", {"src/b.py": "x\n"})
    github.pull(11, "buildwork/issue-1-headers")
    github.pull(12, "buildwork/issue-2-other")
    assert bw("qc", "1", "--allow-hotspot", "public/_headers").code == 0
    result = bw("order")
    assert "Held back" not in result.out
    assert result.out.index("PR #11") < result.out.index("PR #12")
    assert "touches public/_headers" in result.out


def hotspot_wave(repo, github, bw):
    """#1 is sent to change the hotspot, #2 is not. Both are planned and saved."""
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    github.issue(2, "other", body="Change `src/b.py`.")
    assert bw("plan", "--goal", "g", "--issues", "1,2", "--save").code == 0


def test_qc_reads_the_hotspot_permission_from_the_session(repo, github, bw):
    """SKILL.md runs `qc N` bare at collection. The branch sent to change the hotspot must pass."""
    hotspot_wave(repo, github, bw)
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n"})
    result = bw("qc", "1")
    assert result.code == 0, result.out


def test_only_the_issue_sent_to_change_a_hotspot_may_touch_it(repo, github, bw):
    hotspot_wave(repo, github, bw)
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n"})
    repo.branch("buildwork/issue-2-other", {"src/b.py": "x\n", "public/_headers": "y\n"})
    github.pull(11, "buildwork/issue-1-headers")
    github.pull(12, "buildwork/issue-2-other")
    assert bw("qc", "2").code == 2
    result = bw("order")
    assert "Held back, QC not passed: #2" in result.out
    assert "1. PR #11" in result.out


def test_order_without_a_session_knows_no_permission_and_holds_a_hotspot_branch(repo, github, bw):
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n"})
    github.pull(11, "buildwork/issue-1-headers")
    assert "Held back, QC not passed: #1" in bw("order").out


def merged_wave(repo, github, bw):
    """A wave of two where #1 was squash-merged on GitHub and #2 is still open."""
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    repo.merge_on_github("buildwork/issue-1-issue-1")
    github.pull(11, "buildwork/issue-1-issue-1", state="MERGED")
    github.pull(12, "buildwork/issue-2-issue-2")


def test_status_shows_a_merged_pull_request_as_merged(repo, github, bw):
    merged_wave(repo, github, bw)
    result = bw("status")
    assert "Stalled" not in result.out
    assert "Merged - done" in result.out
    assert "#1  merged  buildwork/issue-1-issue-1  PR #11" in result.out


def test_doctor_does_not_call_merged_work_stranded(repo, github, bw):
    merged_wave(repo, github, bw)
    assert "stranded" not in bw("doctor").out


def test_order_leaves_out_merged_and_closed_pull_requests(repo, github, bw):
    merged_wave(repo, github, bw)
    github.issue(3, "issue 3", body="Change `src/f3.py`.")
    repo.branch("buildwork/issue-3-issue-3", {"src/f3.py": "x\n"})
    github.pull(13, "buildwork/issue-3-issue-3", state="CLOSED")
    result = bw("order")
    assert "1. PR #12 (closes #2)" in result.out
    for gone in ("(closes #1)", "issue-1-", "PR #11", "(closes #3)", "issue-3-", "PR #13"):
        assert gone not in result.out


def test_order_says_when_everything_is_already_merged(repo, github, bw):
    merged_wave(repo, github, bw)
    repo.merge_on_github("buildwork/issue-2-issue-2")
    github.pull(12, "buildwork/issue-2-issue-2", state="MERGED")
    result = bw("order")
    assert result.code == 0
    assert "Nothing left to merge" in result.out
    assert "PR #" not in result.out


def test_status_shows_a_closed_pull_request_as_done(repo, github, bw):
    issues(github, 1, 2)
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1", state="CLOSED")
    result = bw("status")
    assert "Closed without merging" in result.out
    assert "Stalled" not in result.out


def test_doctor_warns_when_the_local_base_is_behind_its_remote(repo, github, bw):
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"})
    repo.merge_on_github("buildwork/issue-1-a")
    repo.git("fetch", "-q", "origin")
    assert "behind" in bw("doctor").out


def test_doctor_fetches_before_it_compares(repo, github, bw):
    """Nobody has fetched since the merge on GitHub. doctor must not report a stale comparison."""
    repo.branch("buildwork/issue-1-a", {"a.txt": "a\n"})
    repo.merge_on_github("buildwork/issue-1-a")
    result = bw("doctor")
    assert "Local `main` is 1 commit(s) behind `origin/main`" in result.out


def test_a_later_wave_is_cut_from_a_base_that_contains_the_last_merge(repo, github, bw):
    """Wave 1 merged on GitHub and local main was never pulled. Wave 2 must start after it."""
    issues(github, 1, 2, 3)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.merge_on_github("buildwork/issue-1-issue-1")
    merged = repo.git("rev-parse", "main", cwd=repo.remote).strip()
    assert repo.git("rev-parse", "main").strip() != merged

    payload = bw("plan", "--issues", "2,3", "--json").json()
    assert payload["base_ref"] == "origin/main"
    assert repo.git("rev-parse", payload["base_ref"]).strip() == merged
    assert "cut from origin/main" in bw("plan", "--issues", "2,3").out


def test_plan_stops_when_the_base_cannot_be_fetched(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\nbase = "develop"\n')
    issues(github, 1, 2)
    result = bw("plan", "--issues", "1,2")
    assert result.code == 1
    assert "Could not fetch origin/develop" in result.err
    assert "Wave 1" not in result.out


def test_qc_diffs_against_the_remote_base_not_a_stale_local_one(repo, github, bw):
    """Local main was never pulled after #1 merged. #2's branch must not be charged with #1's file."""
    issues(github, 1, 2)
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n"})
    repo.merge_on_github("buildwork/issue-1-issue-1")
    repo.git("fetch", "-q", "origin")
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"}, base="origin/main")
    result = bw("qc", "2")
    assert result.code == 0, result.out
    assert "src/f1.py" not in result.out


def test_the_brief_names_the_remote_base_it_was_cut_from(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    assert "cut from `origin/main`" in bw("brief", "1").out


def test_an_open_blocker_outside_the_selection_holds_the_issue(repo, github, bw):
    issues(github, 4, 5, 6, 9)
    github.block(4, 9)
    payload = bw("plan", "--issues", "4,5,6", "--json").json()
    assert 4 not in [n for wave in wave_numbers(payload) for n in wave]
    assert any("#9" in w for w in payload["warnings"])


def test_a_held_issue_holds_what_it_blocks(repo, github, bw):
    issues(github, 4, 5, 6, 7, 9)
    github.block(4, 9)
    github.block(5, 4)
    payload = bw("plan", "--issues", "4,5,6,7", "--json").json()
    assert wave_numbers(payload) == [[6, 7]]
    assert "#4 is held: it is blocked by #9, which is open and not in this session." in payload["warnings"]
    assert "#5 is held: it is blocked by #4, which is held too." in payload["warnings"]


def test_a_closed_blocker_outside_the_selection_holds_nothing(repo, github, bw):
    issues(github, 4, 5)
    github.issue(9, "done", state="CLOSED")
    github.block(4, 9)
    payload = bw("plan", "--issues", "4,5", "--json").json()
    assert wave_numbers(payload) == [[4, 5]]
    assert not any("held" in w for w in payload["warnings"])


def test_a_blocker_that_cannot_be_read_is_treated_as_open(repo, github, bw):
    """GitHub's own links carry each blocker's state. A body line does not, so #99 is looked up, and fails."""
    github.blocked_by_field = False
    github.dependencies_api = False
    issues(github, 5, 6)
    github.issue(4, "four", body="Change `src/f4.py`. Blocked by #99.")
    payload = bw("plan", "--issues", "4,5,6", "--json").json()
    assert wave_numbers(payload) == [[5, 6]]
    assert any("#99" in w and "treated as open" in w for w in payload["warnings"])


def test_every_issue_held_is_nothing_to_run_and_says_why(repo, github, bw):
    issues(github, 4, 5, 9)
    github.block(4, 9)
    github.block(5, 9)
    result = bw("plan", "--issues", "4,5")
    assert "DO NOT FAN OUT" in result.out
    assert "waiting on an open blocker" in result.out
    assert "#4 is held" in result.out and "#5 is held" in result.out


def test_a_hold_label_keeps_an_issue_out_whatever_asked_for_it(repo, github, bw):
    repo.configure('enabled = true\nrunner = "paseo"\nhold_labels = ["blocked", "on hold"]\n')
    github.issue(1, "one", body="Change `src/f1.py`.", labels=["blocked"])
    issues(github, 2, 3)
    payload = bw("plan", "--issues", "1,2,3", "--json").json()
    assert wave_numbers(payload) == [[2, 3]]
    assert "#1 is held: it has the `blocked` label." in payload["warnings"]


def test_plan_holds_an_issue_the_roadmap_lists_under_next_and_triage(repo, github, bw):
    repo.on_main("roadmap", {"roadmap.md": (
        "## Next\n\n1. **#1** One\n   Why: first.\n2. **#2** Two\n   Why: second.\n"
        "3. **#3** Three\n   Why: third.\n\n## Later\n\nReady, and not ordered this time.\n\n- **#4** Four\n\n"
        "## Triage\n\nFiled by an agent and not yet reviewed. Listed, never ordered.\n\n- **#3** Three\n"
    )})
    issues(github, 1, 2, 3, 4)
    payload = bw("plan", "--json").json()
    assert wave_numbers(payload) == [[1, 2]]
    assert "#3 is listed under Next and under Triage. A held listing wins, so it is held." in payload["warnings"]


def test_plan_says_when_no_dependency_source_answered(repo, github, bw):
    issues(github, 1, 2)
    github.dependencies_api = False
    github.blocked_by_field = False
    assert "No dependency links were readable" in bw("plan", "--issues", "1,2").out


def test_a_blocker_in_another_repository_is_not_a_local_issue(repo, github, bw):
    issues(github, 1, 2, 3)
    github.block(1, {"repo": "owner/other", "number": 2, "state": "CLOSED"})
    payload = bw("plan", "--issues", "1,2,3", "--json").json()
    assert wave_numbers(payload) == [[1, 2, 3]]


def test_blockers_past_the_first_page_are_read(repo, github, bw):
    for n in range(100, 130):
        github.issue(n, state="CLOSED")
    issues(github, 1, 130)
    github.block(1, *range(100, 131))
    payload = bw("plan", "--issues", "1,130", "--json").json()
    assert wave_numbers(payload) == [[130], [1]]


def test_plan_says_the_blocked_by_field_answered(repo, github, bw):
    issues(github, 1, 2)
    github.block(2, 1)
    payload = bw("plan", "--issues", "1,2", "--json").json()
    assert wave_numbers(payload) == [[1], [2]]
    assert "Dependency links were read from GitHub, through gh's `blockedBy` field." in payload["assumptions"]
    dependency_calls = [c for c in github.calls() if c[:1] == ["api"] and c[1:2] != ["graphql"]]
    assert dependency_calls == [], "one issue list call carries the graph"


def test_an_older_gh_falls_back_to_rest_and_pages_through_it(repo, github, bw):
    """No `blockedBy` field, so REST answers, and blocker 31 is on its second page."""
    github.blocked_by_field = False
    for n in range(100, 130):
        github.issue(n, state="CLOSED")
    issues(github, 1, 130)
    github.block(1, *range(100, 131))
    payload = bw("plan", "--issues", "1,130", "--json").json()
    assert wave_numbers(payload) == [[130], [1]]
    assert "Dependency links were read from GitHub, through the REST dependencies endpoint." in payload["assumptions"]


def test_more_blockers_than_the_field_lists_are_read_from_rest(repo, github, bw):
    """gh asks for the first 50 blockers. The 51st is the open one in this session."""
    for n in range(100, 150):
        github.issue(n, state="CLOSED")
    issues(github, 1, 150)
    github.block(1, *range(100, 151))
    payload = bw("plan", "--issues", "1,150", "--json").json()
    assert wave_numbers(payload) == [[150], [1]]


def test_a_404_from_rest_says_so_and_reads_only_the_body(repo, github, bw):
    github.blocked_by_field = False
    github.dependencies_api = False
    issues(github, 1, 3)
    github.issue(2, "two", body="Change `src/f2.py`. Blocked by #1.")
    payload = bw("plan", "--issues", "1,2,3", "--json").json()
    assert wave_numbers(payload) == [[1, 3], [2]]
    assert any("No dependency links were readable from GitHub" in a for a in payload["assumptions"])
    assert any("Not Found (HTTP 404)" in a for a in payload["assumptions"])


def test_a_bare_after_in_prose_is_not_an_edge(repo, github, bw):
    github.blocked_by_field = False
    github.dependencies_api = False
    issues(github, 1)
    github.issue(2, "two", body="Change `src/f2.py`. Found after #1 shipped.")
    payload = bw("plan", "--issues", "1,2", "--json").json()
    assert wave_numbers(payload) == [[1, 2]]


def test_an_open_blocker_in_another_repository_holds_its_issue(repo, github, bw):
    """Local #2 is open and selected. The blocker is owner/other#2, which is not it."""
    issues(github, 1, 2, 3)
    github.block(1, {"repo": "owner/other", "number": 2, "state": "OPEN"})
    payload = bw("plan", "--issues", "1,2,3", "--json").json()
    assert wave_numbers(payload) == [[2, 3]]
    assert "#1 is held: it is blocked by owner/other#2, which is open in another repository." in payload["warnings"]


def test_a_blocker_in_another_repository_read_through_rest_is_not_local(repo, github, bw):
    github.blocked_by_field = False
    issues(github, 1, 2, 3)
    github.block(1, {"repo": "owner/other", "number": 2, "state": "CLOSED"})
    payload = bw("plan", "--issues", "1,2,3", "--json").json()
    assert wave_numbers(payload) == [[1, 2, 3]]


def test_order_does_not_read_a_blocker_in_another_repository_as_a_branch(repo, github, bw):
    issues(github, 1, 2)
    github.block(2, {"repo": "owner/other", "number": 1, "state": "CLOSED"})
    repo.branch("buildwork/issue-1-issue-1", {"src/f1.py": "x\n" * 50})
    repo.branch("buildwork/issue-2-issue-2", {"src/f2.py": "x\n"})
    github.pull(11, "buildwork/issue-1-issue-1")
    github.pull(12, "buildwork/issue-2-issue-2")
    result = bw("order")
    assert result.out.index("PR #12") < result.out.index("PR #11")
    assert "blocked by #1" not in result.out


def test_auto_runner_without_a_runner_flag_refuses(repo, github, bw):
    repo.configure('enabled = true\nrunner = "auto"\n')
    issues(github, 1, 2)
    result = bw("plan", "--issues", "1,2")
    assert result.code != 0
    assert "--runner" in result.text


def test_auto_runner_takes_the_runner_flag_and_its_cap(repo, github, bw):
    repo.configure('enabled = true\nrunner = "auto"\n')
    issues(github, 1, 2, 3, 4)
    payload = bw("plan", "--issues", "1,2,3,4", "--runner", "paseo", "--json").json()
    assert payload["runner"] == "paseo"
    assert payload["cap"] == 4
    assert wave_numbers(payload) == [[1, 2, 3, 4]]


def test_plan_will_not_take_every_open_issue_without_all(repo, github, bw):
    issues(github, 1, 2, 3)
    result = bw("plan", "--goal", "only the parser")
    assert "Wave 1" not in result.out
    assert "--all" in result.text


def test_plan_refuses_before_it_reads_github_when_nothing_is_selected(repo, github, bw):
    issues(github, 1, 2, 3)
    result = bw("plan", "--goal", "only the parser")
    assert result.code == 1
    assert "every open issue" in result.err
    assert not [c for c in github.calls() if c[:2] == ["issue", "list"]]


def test_plan_with_all_takes_every_open_issue_and_says_so(repo, github, bw):
    issues(github, 1, 2, 3)
    payload = bw("plan", "--all", "--json").json()
    assert payload["source"] == "issues"
    assert sorted(n for wave in wave_numbers(payload) for n in wave) == [1, 2, 3]
    assert any("every open issue in no particular order" in a for a in payload["assumptions"])


def test_plan_with_issues_and_no_roadmap_does_not_claim_every_open_issue(repo, github, bw):
    issues(github, 1, 2, 3)
    payload = bw("plan", "--issues", "2,1", "--json").json()
    assert payload["source"] == "--issues"
    assert not any("every open issue" in a for a in payload["assumptions"])
    assert "The issues were chosen with --issues, and run in the order given." in payload["assumptions"]


def test_plan_with_a_roadmap_needs_neither_issues_nor_all(repo, github, bw):
    repo.on_main("roadmap", {"roadmap.md": "## Next\n\n1. **#1** One\n2. **#2** Two\n"})
    issues(github, 1, 2, 3)
    payload = bw("plan", "--json").json()
    assert wave_numbers(payload) == [[1, 2]]


def test_plan_will_not_take_issues_and_all_together(repo, github, bw):
    issues(github, 1, 2)
    result = bw("plan", "--issues", "1,2", "--all")
    assert result.code != 0
    assert "not allowed with" in result.err


def test_qc_finds_the_branch_after_the_issue_is_retitled(repo, github, bw):
    github.issue(1, "a better title", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-the-original-title", {"src/a.py": "a\n"})
    result = bw("qc", "1")
    assert result.code == 0, result.text
    assert "buildwork/issue-1-the-original-title" in result.out


def test_qc_with_two_branches_for_an_issue_takes_the_one_named_from_its_title(repo, github, bw):
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-an-older-attempt", {"src/stray.py": "s\n"})
    repo.branch("buildwork/issue-1-one", {"src/a.py": "a\n"})
    result = bw("qc", "1")
    assert result.code == 0, result.text
    assert "(buildwork/issue-1-one)" in result.out


def test_qc_with_two_branches_and_neither_from_the_title_asks_which(repo, github, bw):
    github.issue(1, "renamed", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-1-first", {"src/a.py": "a\n"})
    repo.branch("buildwork/issue-1-second", {"src/a.py": "b\n"})
    result = bw("qc", "1")
    assert result.code == 1
    assert "2 buildwork branches" in result.err and "--branch" in result.err


def test_qc_does_not_take_another_issues_branch(repo, github, bw):
    """#1's number is a prefix of #12's. Matching is on the whole number."""
    github.issue(1, "one", body="Change `src/a.py`.")
    repo.branch("buildwork/issue-12-twelve", {"src/a.py": "a\n"})
    result = bw("qc", "1")
    assert result.code == 1
    assert "No branch for #1" in result.err


def test_status_from_a_linked_worktree_finds_the_session(repo, github, bw, tmp_path):
    issues(github, 1, 2)
    bw("plan", "--goal", "from the main checkout", "--issues", "1,2", "--save")
    repo.git("branch", "orchestrator", "main")
    linked = repo.worktree(tmp_path / "orchestrator-checkout", "orchestrator")
    assert "Session: from the main checkout" in bw("status", cwd=linked).out


def test_qc_from_a_linked_worktree_reads_the_hotspot_permission_saved_from_the_main_checkout(repo, github, bw, tmp_path):
    repo.configure(HOTSPOT)
    github.issue(1, "headers", body="Change `public/_headers`.")
    github.issue(2, "other", body="Change `src/other.py`.")
    bw("plan", "--goal", "g", "--issues", "1,2", "--save")
    repo.branch("buildwork/issue-1-headers", {"public/_headers": "x\n"})
    repo.git("branch", "orchestrator", "main")
    linked = repo.worktree(tmp_path / "orchestrator-checkout", "orchestrator")
    result = bw("qc", "1", cwd=linked)
    assert result.code == 0, result.text


def test_two_repositories_with_the_same_folder_name_keep_separate_sessions(repo, github, bw, tmp_path, home):
    other_gh = FakeGitHub(home=tmp_path / "gh-other", repo="owner/other")
    other = Repo(tmp_path / "elsewhere", isolated_env(home))
    assert other.root.name == repo.root.name
    for fake in (github, other_gh):
        issues(fake, 1, 2)

    env = {**os.environ, **isolated_env(home), **other_gh.env()}
    subprocess.run(
        [sys.executable, str(BUILDWORK), "plan", "--goal", "the other one", "--issues", "1,2", "--save"],
        cwd=other.root, env=env, capture_output=True, text=True, check=True,
    )
    bw("plan", "--goal", "this one", "--issues", "1,2", "--save")
    result = subprocess.run(
        [sys.executable, str(BUILDWORK), "status"],
        cwd=other.root, env=env, capture_output=True, text=True, check=True,
    )
    assert "Session: the other one" in result.stdout
