import roadmap

# What deskwork's roadmap.render() writes today, section for section: Next is
# numbered with a reason line under some entries, Blocked names its blockers
# inline, Cycles and Bottlenecks mention issues that are also listed
# elsewhere, and Triage is bulleted with titles under an explanatory line.
DESKWORK_SHAPE = """\
# Roadmap

Generated by deskwork on 2026-09-17 from 9 open issues.
Order is reasoned, not computed. Every dependency shown is a declared GitHub link.

## Next

1. **#143** The GitHub metadata register has drifted on four repos
   Nothing blocks it, and #144 cannot start until it lands.
2. **#145** The positioning changed
   Reasoned ahead of #147 because the register pass and the copy pass fight if interleaved.

## Blocked

- **#144** Rewrite the copy - blocked by #143
- **#36** Settle the line - blocked by #143, blocked by owner/other#26

## Cycles

These block each other. Nothing can be ordered until one link goes.

- #150 -> #151 -> #150

## Bottlenecks

- **#143** blocks 2 issues

## Triage - not yet in the roadmap

Filed by an agent and not yet reviewed. Listed, never ordered.

- #146 Something an agent noticed
- #147 Another thing an agent noticed
"""

# What deskwork's rebuilt roadmap.render() writes, from 25 Sep 2026. Next holds
# only what was ordered, each with a `Why:` line under it. Anything ready but
# not ordered goes under Later, and the Triage heading is plain `## Triage`.
# Only the ordered Next items may come out runnable.
DESKWORK_REBUILT = """\
# Roadmap

Generated by deskwork on 2026-09-25 from 11 open issues.
Next is the order an agent reasoned, with the reason under each item. Every dependency shown is a declared GitHub link.

## Next

1. **#143** The GitHub metadata register has drifted on four repos
   Why: Nothing blocks it, and #144 cannot start until it lands.
2. **#145** The positioning changed
   Why: 2. Ahead of #147, because the register pass and the copy pass fight if interleaved.

## Blocked

- **#144** Rewrite the copy - blocked by #143
- **#36** Settle the line - blocked by #143, blocked by owner/other#26

## Later

Ready, and not ordered this time.

- **#148** Tidy the footer
- **#149** Follow-up to #143

## Cycles

These block each other. Nothing in a cycle can start until one link goes.

- #150 -> #151 -> #150

## Bottlenecks

- **#143** blocks 2 issues

## Triage

Filed by an agent and not yet reviewed. Listed, never ordered.

- **#146** Something an agent noticed
- **#147** Another thing an agent noticed
"""

# deskwork has listed one issue under both Next and Triage. Whichever comes
# first, it must be held: nothing unreviewed enters the order.
LISTED_TWICE = """\
## Next

1. **#143** Reviewed and ready
2. **#148** Filed by an agent a minute ago

## Triage - not yet in the roadmap

Filed by an agent and not yet reviewed. Listed, never ordered.

- #148 Filed by an agent a minute ago
"""


def test_reads_next_in_order():
    board = roadmap.parse(DESKWORK_SHAPE)
    assert [e.number for e in board.runnable] == [143, 145]


def test_reasoning_lines_are_not_entries():
    """`#144 cannot start` and `ahead of #147` are prose, not queue items.

    Reading them as entries would silently double the queue and dispatch an
    agent at an issue the roadmap never listed.
    """
    board = roadmap.parse(DESKWORK_SHAPE)
    numbers = [e.number for e in board.entries]
    assert numbers.count(143) == 1
    assert numbers.count(147) == 1
    assert [e.number for e in board.runnable] == [143, 145]


def test_blocked_section_is_not_runnable():
    board = roadmap.parse(DESKWORK_SHAPE)
    blocked = [e for e in board.entries if e.section.startswith("blocked")]
    assert [e.number for e in blocked] == [144, 36]
    assert all(not e.runnable for e in blocked)


def test_cycles_and_bottlenecks_are_never_runnable():
    board = roadmap.parse(DESKWORK_SHAPE)
    runnable = [e.number for e in board.runnable]
    assert 150 not in runnable and 151 not in runnable


def test_triage_is_never_runnable():
    """deskwork's rule: nothing filed unreviewed enters the order."""
    board = roadmap.parse(DESKWORK_SHAPE)
    triage = [e for e in board.entries if e.section.startswith("triage")]
    assert triage
    assert all(not e.runnable for e in triage)


def test_cross_repo_reference_is_not_a_local_issue():
    """`owner/other#26` must never become local issue 26."""
    board = roadmap.parse(DESKWORK_SHAPE)
    assert 26 not in [e.number for e in board.entries]


def test_titles_are_kept():
    board = roadmap.parse(DESKWORK_SHAPE)
    first = board.runnable[0]
    assert first.number == 143
    assert "metadata register" in first.title
    triage = next(e for e in board.entries if e.number == 146)
    assert triage.title == "Something an agent noticed"


def test_an_all_blocked_roadmap_has_nothing_to_run():
    """deskwork writes a sentence, not an entry, when nothing is ready."""
    text = "## Next\n\nNothing is ready. Everything open is blocked.\n\n## Blocked\n\n- **#2** Two - blocked by #1\n"
    board = roadmap.parse(text)
    assert board.runnable == ()
    assert [e.number for e in board.entries] == [2]


def test_an_issue_under_both_next_and_triage_is_held():
    board = roadmap.parse(LISTED_TWICE)
    assert [e.number for e in board.runnable] == [143]


def test_the_held_listing_wins_whichever_comes_first():
    text = "## Triage\n\n- **#148** Filed a minute ago\n\n## Next\n\n1. **#143** Ready\n2. **#148** Filed a minute ago\n"
    board = roadmap.parse(text)
    assert [e.number for e in board.runnable] == [143]
    held = next(e for e in board.entries if e.number == 148)
    assert held.section == "triage"


def test_an_issue_listed_twice_is_named_in_a_warning():
    board = roadmap.parse(LISTED_TWICE)
    assert board.warnings == (
        "#148 is listed under Next and under Triage. A held listing wins, so it is held.",
    )


def test_a_bottleneck_mention_does_not_hold_an_issue_next_runs():
    """Bottlenecks names what most needs to go first. It describes; it does not place."""
    board = roadmap.parse(DESKWORK_SHAPE)
    assert 143 in [e.number for e in board.runnable]
    assert board.warnings == ()


# --- deskwork's rebuilt output ----------------------------------------------

def test_rebuilt_roadmap_runs_only_the_ordered_next_items():
    board = roadmap.parse(DESKWORK_REBUILT)
    assert [e.number for e in board.runnable] == [143, 145]
    assert board.warnings == ()


def test_rebuilt_roadmap_holds_later():
    board = roadmap.parse(DESKWORK_REBUILT)
    later = [e for e in board.entries if e.section.startswith("later")]
    assert [e.number for e in later] == [148, 149]
    assert not any(e.runnable for e in later)
    assert next(e for e in later if e.number == 149).title == "Follow-up to #143"


def test_rebuilt_roadmap_holds_a_plain_triage_heading():
    board = roadmap.parse(DESKWORK_REBUILT)
    triage = [e for e in board.entries if e.section == "triage"]
    assert [e.number for e in triage] == [146, 147]
    assert not any(e.runnable for e in triage)


def test_why_lines_are_not_entries():
    """`Why:` lines mention #144 and #147, and one starts with a number. None is an entry."""
    board = roadmap.parse(DESKWORK_REBUILT)
    numbers = [e.number for e in board.entries]
    assert numbers == [143, 145, 144, 36, 148, 149, 150, 146, 147]
    assert next(e for e in board.entries if e.number == 145).title == "The positioning changed"


def test_the_old_triage_heading_is_still_held():
    board = roadmap.parse("## Next\n\n1. **#1** One\n\n## Triage - not yet in the roadmap\n\n- #2 Two\n")
    assert [e.number for e in board.runnable] == [1]
    assert [e.number for e in board.entries] == [1, 2]


def test_unknown_heading_is_held_not_run():
    text = "## Someday maybe\n\n- #99 a thing\n"
    board = roadmap.parse(text)
    assert [e.number for e in board.entries] == [99]
    assert board.runnable == ()


def test_items_before_any_heading_are_ignored():
    text = "- #5 orphan\n\n## Next\n\n- #6 real\n"
    board = roadmap.parse(text)
    assert [e.number for e in board.entries] == [6]


def test_load_falls_back_to_open_issues_and_says_so(tmp_path):
    board = roadmap.load(
        tmp_path / "roadmap.md",
        fallback_issues=[{"number": 1, "title": "one"}, {"number": 2, "title": "two"}],
    )
    assert board.source == "issues"
    assert [e.number for e in board.runnable] == [1, 2]
    assert "no particular order" in board.note


def test_load_reads_the_file_when_present(tmp_path):
    path = tmp_path / "roadmap.md"
    path.write_text(DESKWORK_SHAPE, encoding="utf-8")
    board = roadmap.load(path, fallback_issues=[{"number": 999, "title": "ignored"}])
    assert board.source == "roadmap.md"
    assert 999 not in [e.number for e in board.entries]


def test_empty_roadmap_is_reported_not_silently_empty(tmp_path):
    path = tmp_path / "roadmap.md"
    path.write_text("# Roadmap\n\nNothing yet.\n", encoding="utf-8")
    board = roadmap.load(path, fallback_issues=[{"number": 1, "title": "x"}])
    assert board.entries == ()
    assert "no issue entries" in board.note
