import roadmap
from harness import bug

# What deskwork's roadmap.render() writes today, section for section: Next is
# numbered with a reason line under some entries, Blocked names its blockers
# inline, Cycles and Bottlenecks mention issues that are also listed
# elsewhere, and Triage is bulleted with titles under an explanatory line.
DESKWORK_SHAPE = """\
# Roadmap

Generated by deskwork on 2026-09-17 from 9 open issues.
Order is reasoned, not computed. Every dependency shown is a declared GitHub link.

## Next

1. **#143** The GitHub metadata register has drifted on four repos
   Nothing blocks it, and #144 cannot start until it lands.
2. **#145** The positioning changed
   Reasoned ahead of #147 because the register pass and the copy pass fight if interleaved.

## Blocked

- **#144** Rewrite the copy - blocked by #143
- **#36** Settle the line - blocked by #143, blocked by owner/other#26

## Cycles

These block each other. Nothing can be ordered until one link goes.

- #150 -> #151 -> #150

## Bottlenecks

- **#143** blocks 2 issues

## Triage - not yet in the roadmap

Filed by an agent and not yet reviewed. Listed, never ordered.

- #146 Something an agent noticed
- #147 Another thing an agent noticed
"""

# deskwork has listed one issue under both Next and Triage. Whichever comes
# first, it must be held: nothing unreviewed enters the order.
LISTED_TWICE = """\
## Next

1. **#143** Reviewed and ready
2. **#148** Filed by an agent a minute ago

## Triage - not yet in the roadmap

Filed by an agent and not yet reviewed. Listed, never ordered.

- #148 Filed by an agent a minute ago
"""


def test_reads_next_in_order():
    board = roadmap.parse(DESKWORK_SHAPE)
    assert [e.number for e in board.runnable] == [143, 145]


def test_reasoning_lines_are_not_entries():
    """`#144 cannot start` and `ahead of #147` are prose, not queue items.

    Reading them as entries would silently double the queue and dispatch an
    agent at an issue the roadmap never listed.
    """
    board = roadmap.parse(DESKWORK_SHAPE)
    numbers = [e.number for e in board.entries]
    assert numbers.count(143) == 1
    assert numbers.count(147) == 1
    assert [e.number for e in board.runnable] == [143, 145]


def test_blocked_section_is_not_runnable():
    board = roadmap.parse(DESKWORK_SHAPE)
    blocked = [e for e in board.entries if e.section.startswith("blocked")]
    assert [e.number for e in blocked] == [144, 36]
    assert all(not e.runnable for e in blocked)


def test_cycles_and_bottlenecks_are_never_runnable():
    board = roadmap.parse(DESKWORK_SHAPE)
    runnable = [e.number for e in board.runnable]
    assert 150 not in runnable and 151 not in runnable


def test_triage_is_never_runnable():
    """deskwork's rule: nothing filed unreviewed enters the order."""
    board = roadmap.parse(DESKWORK_SHAPE)
    triage = [e for e in board.entries if e.section.startswith("triage")]
    assert triage
    assert all(not e.runnable for e in triage)


def test_cross_repo_reference_is_not_a_local_issue():
    """`owner/other#26` must never become local issue 26."""
    board = roadmap.parse(DESKWORK_SHAPE)
    assert 26 not in [e.number for e in board.entries]


def test_titles_are_kept():
    board = roadmap.parse(DESKWORK_SHAPE)
    first = board.runnable[0]
    assert first.number == 143
    assert "metadata register" in first.title
    triage = next(e for e in board.entries if e.number == 146)
    assert triage.title == "Something an agent noticed"


def test_an_all_blocked_roadmap_has_nothing_to_run():
    """deskwork writes a sentence, not an entry, when nothing is ready."""
    text = "## Next\n\nNothing is ready. Everything open is blocked.\n\n## Blocked\n\n- **#2** Two - blocked by #1\n"
    board = roadmap.parse(text)
    assert board.runnable == ()
    assert [e.number for e in board.entries] == [2]


@bug(10)
def test_an_issue_under_both_next_and_triage_is_held():
    board = roadmap.parse(LISTED_TWICE)
    assert [e.number for e in board.runnable] == [143]


def test_unknown_heading_is_held_not_run():
    text = "## Someday maybe\n\n- #99 a thing\n"
    board = roadmap.parse(text)
    assert [e.number for e in board.entries] == [99]
    assert board.runnable == ()


def test_items_before_any_heading_are_ignored():
    text = "- #5 orphan\n\n## Next\n\n- #6 real\n"
    board = roadmap.parse(text)
    assert [e.number for e in board.entries] == [6]


def test_load_falls_back_to_open_issues_and_says_so(tmp_path):
    board = roadmap.load(
        tmp_path / "roadmap.md",
        fallback_issues=[{"number": 1, "title": "one"}, {"number": 2, "title": "two"}],
    )
    assert board.source == "issues"
    assert [e.number for e in board.runnable] == [1, 2]
    assert "no particular order" in board.note


def test_load_reads_the_file_when_present(tmp_path):
    path = tmp_path / "roadmap.md"
    path.write_text(DESKWORK_SHAPE, encoding="utf-8")
    board = roadmap.load(path, fallback_issues=[{"number": 999, "title": "ignored"}])
    assert board.source == "roadmap.md"
    assert 999 not in [e.number for e in board.entries]


def test_empty_roadmap_is_reported_not_silently_empty(tmp_path):
    path = tmp_path / "roadmap.md"
    path.write_text("# Roadmap\n\nNothing yet.\n", encoding="utf-8")
    board = roadmap.load(path, fallback_issues=[{"number": 1, "title": "x"}])
    assert board.entries == ()
    assert "no issue entries" in board.note
