import roadmap

DESKWORK_SHAPE = """\
# Roadmap

Generated by deskwork on 2026-09-17 from 14 open issues (#100-#147).
Order is reasoned, not computed. Every dependency shown is a declared GitHub link.

## Next

1. **#143** The GitHub metadata register has drifted on four repos
   Nothing blocks it, and #144 cannot start until it lands.
2. **#144** Terraken's positioning changed
   blocked by #143
   Reasoned ahead of #147 because the register pass and the copy pass fight if interleaved.

## Blocked

- **#36** Settle the line - blocked by dbhq-uk/terraken#26

## Triage - not yet in the roadmap

- #146
- #147
"""


def test_reads_next_in_order():
    board = roadmap.parse(DESKWORK_SHAPE)
    assert [e.number for e in board.runnable] == [143, 144]


def test_reasoning_lines_are_not_entries():
    """`blocked by #143` and `ahead of #147` are prose, not queue items.

    Reading them as entries would silently double the queue and dispatch an
    agent at an issue the roadmap never listed.
    """
    board = roadmap.parse(DESKWORK_SHAPE)
    numbers = [e.number for e in board.entries]
    assert numbers.count(143) == 1
    assert numbers.count(147) == 1
    assert [e.number for e in board.runnable] == [143, 144]


def test_blocked_section_is_not_runnable():
    board = roadmap.parse(DESKWORK_SHAPE)
    blocked = [e for e in board.entries if e.section.startswith("blocked")]
    assert blocked == [] or all(not e.runnable for e in blocked)


def test_triage_is_never_runnable():
    """deskwork's rule: nothing filed unreviewed enters the order."""
    board = roadmap.parse(DESKWORK_SHAPE)
    triage = [e for e in board.entries if e.section.startswith("triage")]
    assert triage
    assert all(not e.runnable for e in triage)


def test_cross_repo_reference_is_not_a_local_issue():
    """`dbhq-uk/terraken#26` must never become local issue 26."""
    board = roadmap.parse(DESKWORK_SHAPE)
    assert 26 not in [e.number for e in board.entries]


def test_titles_are_kept():
    board = roadmap.parse(DESKWORK_SHAPE)
    first = board.runnable[0]
    assert first.number == 143
    assert "metadata register" in first.title


def test_unknown_heading_is_held_not_run():
    text = "## Someday maybe\n\n- #99 a thing\n"
    board = roadmap.parse(text)
    assert [e.number for e in board.entries] == [99]
    assert board.runnable == ()


def test_items_before_any_heading_are_ignored():
    text = "- #5 orphan\n\n## Next\n\n- #6 real\n"
    board = roadmap.parse(text)
    assert [e.number for e in board.entries] == [6]


def test_load_falls_back_to_open_issues_and_says_so(tmp_path):
    board = roadmap.load(
        tmp_path / "roadmap.md",
        fallback_issues=[{"number": 1, "title": "one"}, {"number": 2, "title": "two"}],
    )
    assert board.source == "issues"
    assert [e.number for e in board.runnable] == [1, 2]
    assert "no particular order" in board.note


def test_load_reads_the_file_when_present(tmp_path):
    path = tmp_path / "roadmap.md"
    path.write_text(DESKWORK_SHAPE, encoding="utf-8")
    board = roadmap.load(path, fallback_issues=[{"number": 999, "title": "ignored"}])
    assert board.source == "roadmap.md"
    assert 999 not in [e.number for e in board.entries]


def test_empty_roadmap_is_reported_not_silently_empty(tmp_path):
    path = tmp_path / "roadmap.md"
    path.write_text("# Roadmap\n\nNothing yet.\n", encoding="utf-8")
    board = roadmap.load(path, fallback_issues=[{"number": 1, "title": "x"}])
    assert board.entries == ()
    assert "no issue entries" in board.note
